export const reviewedCards = [
  {
    id: 217,
    user: {
      id: 1,
      name: 'Joe',
      role: 'admin',
      updatedAt: '2024-08-07T00:15:21.065Z',
      createdAt: '2024-07-06T01:23:24.760Z',
      email: 'hello@joeholmes.dev',
      _verified: true,
      loginAttempts: 0,
    },
    userLesson: {
      id: 32,
      user: {
        id: 1,
        name: 'Joe',
        role: 'admin',
        updatedAt: '2024-08-07T00:15:21.065Z',
        createdAt: '2024-07-06T01:23:24.760Z',
        email: 'hello@joeholmes.dev',
        _verified: true,
        loginAttempts: 0,
      },
      lesson: {
        id: 6,
        title: 'Confirmation Bias',
        slug: 'confirmation-bias',
        course: 3,
        number: null,
        disabled: null,
        youTubeId: null,
        exposition: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Person looking at before/after diet photos, ignoring negative reviews> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Diagram: Circular arrow showing how confirmation bias feeds into itself> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
            ],
            direction: 'ltr',
          },
        },
        exposition_html:
          "<p>Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. </p><p><Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> </p><p>This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. </p><p><Image: Person looking at before/after diet photos, ignoring negative reviews> </p><p>This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. </p><p><Diagram: Circular arrow showing how confirmation bias feeds into itself> </p><p>To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.</p>",
        review: [
          {
            id: '66a2eaec8f8e85ebe8356b12',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'What is confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>What is confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebbf8f8e85ebe8356b13',
                answerText:
                  "The tendency to forget information that doesn't align with our beliefs",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ebc68f8e85ebe8356b14',
                answerText:
                  'The tendency to seek, interpret, and remember information that confirms our existing beliefs',
                isCorrect: true,
                answerMessage: null,
              },
              {
                id: '66a2ebcf8f8e85ebe8356b15',
                answerText: 'The tendency to change our beliefs based on new information',
                isCorrect: false,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ebde8f8e85ebe8356b16',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which of the following is NOT a way confirmation bias can lead us astray?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html:
              '<p>Which of the following is NOT a way confirmation bias can lead us astray?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebf98f8e85ebe8356b17',
                answerText:
                  "It can make our beliefs less robust to counter-arguments, since they haven't been exposed to strong criticisms",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec098f8e85ebe8356b18',
                answerText:
                  "It can cause us to miss crucial information in decision-making, since we won't notice information that challenges us",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec3c8f8e85ebe8356b19',
                answerText:
                  'It can cause us to lose confidence in our positions, due to focusing on what challenges them',
                isCorrect: true,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ec758f8e85ebe8356b1a',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which scenario demonstrates confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>Which scenario demonstrates confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ec958f8e85ebe8356b1b',
                answerText:
                  'A scientist changes their hypothesis after finding contradictory evidence',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec9c8f8e85ebe8356b1c',
                answerText:
                  'A voter watches debates from all political parties before deciding who to vote for',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2eca68f8e85ebe8356b1d',
                answerText:
                  "An investor reads only positive news about a company they've invested in, ignoring negative reports",
                isCorrect: true,
                answerMessage:
                  'Good! This investor is sleepwalking to disaster, by not exposing themselves to information that challenges them.',
              },
            ],
            blockType: 'multChoice',
          },
        ],
        atom: {
          shortSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          shortSummary_html:
            '<p>Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.</p>',
          mediumSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'ul',
                  type: 'list',
                  start: 1,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      value: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 2,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 3,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                  ],
                  listType: 'bullet',
                  direction: 'ltr',
                },
              ],
              direction: 'ltr',
            },
          },
          mediumSummary_html:
            '<ul class="list-bullet"><li value=1>Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.</li><li value=2>This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.</li><li value=3>To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.</li></ul>',
          longSummary: null,
          longSummary_html: '',
          source: 5,
          specificSection: ' 2.2 Overcoming Cognitive Biases and Engaging in Critical Reflection',
        },
        flashcards: [13, 14, 17],
        updatedAt: '2024-08-02T11:02:37.884Z',
        createdAt: '2024-07-25T22:54:55.824Z',
      },
      currentPhase: {
        id: 1,
        name: 'Recall',
        description: null,
        stabilityThreshold: 14,
        stage: 1,
        updatedAt: '2024-08-02T10:54:45.823Z',
        createdAt: '2024-08-02T10:54:45.823Z',
      },
      isCompleted: true,
      updatedAt: '2024-08-05T14:01:23.954Z',
      createdAt: '2024-08-05T14:01:23.954Z',
    },
    flashcard: {
      id: 13,
      title: 'Ignoring Contradictory Beliefs',
      question:
        'Our tendency to ignore or dismiss evidence that contradicts our beliefs is part of what cognitive bias?',
      answer: 'Confirmation bias',
      lesson: {
        id: 6,
        title: 'Confirmation Bias',
        slug: 'confirmation-bias',
        course: 3,
        number: null,
        disabled: null,
        youTubeId: null,
        exposition: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Person looking at before/after diet photos, ignoring negative reviews> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Diagram: Circular arrow showing how confirmation bias feeds into itself> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
            ],
            direction: 'ltr',
          },
        },
        exposition_html:
          "<p>Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. </p><p><Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> </p><p>This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. </p><p><Image: Person looking at before/after diet photos, ignoring negative reviews> </p><p>This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. </p><p><Diagram: Circular arrow showing how confirmation bias feeds into itself> </p><p>To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.</p>",
        review: [
          {
            id: '66a2eaec8f8e85ebe8356b12',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'What is confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>What is confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebbf8f8e85ebe8356b13',
                answerText:
                  "The tendency to forget information that doesn't align with our beliefs",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ebc68f8e85ebe8356b14',
                answerText:
                  'The tendency to seek, interpret, and remember information that confirms our existing beliefs',
                isCorrect: true,
                answerMessage: null,
              },
              {
                id: '66a2ebcf8f8e85ebe8356b15',
                answerText: 'The tendency to change our beliefs based on new information',
                isCorrect: false,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ebde8f8e85ebe8356b16',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which of the following is NOT a way confirmation bias can lead us astray?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html:
              '<p>Which of the following is NOT a way confirmation bias can lead us astray?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebf98f8e85ebe8356b17',
                answerText:
                  "It can make our beliefs less robust to counter-arguments, since they haven't been exposed to strong criticisms",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec098f8e85ebe8356b18',
                answerText:
                  "It can cause us to miss crucial information in decision-making, since we won't notice information that challenges us",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec3c8f8e85ebe8356b19',
                answerText:
                  'It can cause us to lose confidence in our positions, due to focusing on what challenges them',
                isCorrect: true,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ec758f8e85ebe8356b1a',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which scenario demonstrates confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>Which scenario demonstrates confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ec958f8e85ebe8356b1b',
                answerText:
                  'A scientist changes their hypothesis after finding contradictory evidence',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec9c8f8e85ebe8356b1c',
                answerText:
                  'A voter watches debates from all political parties before deciding who to vote for',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2eca68f8e85ebe8356b1d',
                answerText:
                  "An investor reads only positive news about a company they've invested in, ignoring negative reports",
                isCorrect: true,
                answerMessage:
                  'Good! This investor is sleepwalking to disaster, by not exposing themselves to information that challenges them.',
              },
            ],
            blockType: 'multChoice',
          },
        ],
        atom: {
          shortSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          shortSummary_html:
            '<p>Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.</p>',
          mediumSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'ul',
                  type: 'list',
                  start: 1,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      value: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 2,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 3,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                  ],
                  listType: 'bullet',
                  direction: 'ltr',
                },
              ],
              direction: 'ltr',
            },
          },
          mediumSummary_html:
            '<ul class="list-bullet"><li value=1>Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.</li><li value=2>This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.</li><li value=3>To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.</li></ul>',
          longSummary: null,
          longSummary_html: '',
          source: 5,
          specificSection: ' 2.2 Overcoming Cognitive Biases and Engaging in Critical Reflection',
        },
        flashcards: [13, 14, 17],
        updatedAt: '2024-08-02T11:02:37.884Z',
        createdAt: '2024-07-25T22:54:55.824Z',
      },
      learningPhase: {
        id: 1,
        name: 'Recall',
        description: null,
        stabilityThreshold: 14,
        stage: 1,
        updatedAt: '2024-08-02T10:54:45.823Z',
        createdAt: '2024-08-02T10:54:45.823Z',
      },
      updatedAt: '2024-08-02T10:56:13.627Z',
      createdAt: '2024-07-27T00:56:19.237Z',
    },
    current: {
      due: '2024-08-20T00:20:20.090Z',
      reps: 2,
      state: 2,
      lapses: 0,
      stability: 14.01466145,
      difficulty: 3.98716172,
      last_review: '2024-08-07T00:20:20.090Z',
      elapsed_days: 1,
      scheduled_days: 13,
    },
    log: [
      {
        due: '2024-08-05T14:01:44.256Z',
        state: 2,
        rating: 3,
        review: '2024-08-07T00:20:20.090Z',
        stability: 10.9355,
        difficulty: 3.9437,
        elapsed_days: 1,
        scheduled_days: 11,
        last_elapsed_days: 0,
      },
      {
        due: '2024-08-05T14:01:24.247Z',
        state: 0,
        rating: 4,
        review: '2024-08-05T14:01:44.256Z',
        stability: 14,
        difficulty: 0,
        elapsed_days: 0,
        scheduled_days: 0,
        last_elapsed_days: 0,
      },
    ],
    updatedAt: '2024-08-07T00:20:20.221Z',
    createdAt: '2024-08-05T14:01:24.263Z',
  },
  {
    id: 218,
    user: {
      id: 1,
      name: 'Joe',
      role: 'admin',
      updatedAt: '2024-08-07T00:15:21.065Z',
      createdAt: '2024-07-06T01:23:24.760Z',
      email: 'hello@joeholmes.dev',
      _verified: true,
      loginAttempts: 0,
    },
    userLesson: {
      id: 32,
      user: {
        id: 1,
        name: 'Joe',
        role: 'admin',
        updatedAt: '2024-08-07T00:15:21.065Z',
        createdAt: '2024-07-06T01:23:24.760Z',
        email: 'hello@joeholmes.dev',
        _verified: true,
        loginAttempts: 0,
      },
      lesson: {
        id: 6,
        title: 'Confirmation Bias',
        slug: 'confirmation-bias',
        course: 3,
        number: null,
        disabled: null,
        youTubeId: null,
        exposition: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Person looking at before/after diet photos, ignoring negative reviews> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Diagram: Circular arrow showing how confirmation bias feeds into itself> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
            ],
            direction: 'ltr',
          },
        },
        exposition_html:
          "<p>Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. </p><p><Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> </p><p>This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. </p><p><Image: Person looking at before/after diet photos, ignoring negative reviews> </p><p>This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. </p><p><Diagram: Circular arrow showing how confirmation bias feeds into itself> </p><p>To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.</p>",
        review: [
          {
            id: '66a2eaec8f8e85ebe8356b12',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'What is confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>What is confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebbf8f8e85ebe8356b13',
                answerText:
                  "The tendency to forget information that doesn't align with our beliefs",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ebc68f8e85ebe8356b14',
                answerText:
                  'The tendency to seek, interpret, and remember information that confirms our existing beliefs',
                isCorrect: true,
                answerMessage: null,
              },
              {
                id: '66a2ebcf8f8e85ebe8356b15',
                answerText: 'The tendency to change our beliefs based on new information',
                isCorrect: false,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ebde8f8e85ebe8356b16',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which of the following is NOT a way confirmation bias can lead us astray?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html:
              '<p>Which of the following is NOT a way confirmation bias can lead us astray?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebf98f8e85ebe8356b17',
                answerText:
                  "It can make our beliefs less robust to counter-arguments, since they haven't been exposed to strong criticisms",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec098f8e85ebe8356b18',
                answerText:
                  "It can cause us to miss crucial information in decision-making, since we won't notice information that challenges us",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec3c8f8e85ebe8356b19',
                answerText:
                  'It can cause us to lose confidence in our positions, due to focusing on what challenges them',
                isCorrect: true,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ec758f8e85ebe8356b1a',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which scenario demonstrates confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>Which scenario demonstrates confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ec958f8e85ebe8356b1b',
                answerText:
                  'A scientist changes their hypothesis after finding contradictory evidence',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec9c8f8e85ebe8356b1c',
                answerText:
                  'A voter watches debates from all political parties before deciding who to vote for',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2eca68f8e85ebe8356b1d',
                answerText:
                  "An investor reads only positive news about a company they've invested in, ignoring negative reports",
                isCorrect: true,
                answerMessage:
                  'Good! This investor is sleepwalking to disaster, by not exposing themselves to information that challenges them.',
              },
            ],
            blockType: 'multChoice',
          },
        ],
        atom: {
          shortSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          shortSummary_html:
            '<p>Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.</p>',
          mediumSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'ul',
                  type: 'list',
                  start: 1,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      value: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 2,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 3,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                  ],
                  listType: 'bullet',
                  direction: 'ltr',
                },
              ],
              direction: 'ltr',
            },
          },
          mediumSummary_html:
            '<ul class="list-bullet"><li value=1>Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.</li><li value=2>This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.</li><li value=3>To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.</li></ul>',
          longSummary: null,
          longSummary_html: '',
          source: 5,
          specificSection: ' 2.2 Overcoming Cognitive Biases and Engaging in Critical Reflection',
        },
        flashcards: [13, 14, 17],
        updatedAt: '2024-08-02T11:02:37.884Z',
        createdAt: '2024-07-25T22:54:55.824Z',
      },
      currentPhase: {
        id: 1,
        name: 'Recall',
        description: null,
        stabilityThreshold: 14,
        stage: 1,
        updatedAt: '2024-08-02T10:54:45.823Z',
        createdAt: '2024-08-02T10:54:45.823Z',
      },
      isCompleted: true,
      updatedAt: '2024-08-05T14:01:23.954Z',
      createdAt: '2024-08-05T14:01:23.954Z',
    },
    flashcard: {
      id: 14,
      title: 'Information Chosen Via Confirmation Bias',
      question: 'Confirmation bias involves seeking out what type of information?',
      answer: 'Information that confirms our existing beliefs',
      lesson: {
        id: 6,
        title: 'Confirmation Bias',
        slug: 'confirmation-bias',
        course: 3,
        number: null,
        disabled: null,
        youTubeId: null,
        exposition: {
          root: {
            type: 'root',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. ",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Image: Person looking at before/after diet photos, ignoring negative reviews> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: 'This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: '<Diagram: Circular arrow showing how confirmation bias feeds into itself> ',
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
              {
                type: 'paragraph',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    mode: 'normal',
                    text: "To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.",
                    type: 'text',
                    style: '',
                    detail: 0,
                    format: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                textFormat: 0,
              },
            ],
            direction: 'ltr',
          },
        },
        exposition_html:
          "<p>Confirmation bias is our brain's tendency to seek out, interpret, and remember information that confirms our existing beliefs while ignoring or dismissing contradictory evidence. </p><p><Image: Split screen showing a person reading news on their phone, one side highlighting positive headlines, the other showing ignored negative headlines> </p><p>This bias can significantly impact our decision-making and worldview. For instance, if you believe a certain diet is healthy, you're more likely to notice and remember success stories about that diet while overlooking potential drawbacks or failures. </p><p><Image: Person looking at before/after diet photos, ignoring negative reviews> </p><p>This bias can be particularly dangerous in the age of social media, where algorithms often show us content that aligns with our existing views, creating echo chambers that reinforce our beliefs. </p><p><Diagram: Circular arrow showing how confirmation bias feeds into itself> </p><p>To combat confirmation bias, we must actively seek out diverse perspectives, look for news we don't want to hear, and challenge our own assumptions.</p>",
        review: [
          {
            id: '66a2eaec8f8e85ebe8356b12',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'What is confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>What is confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebbf8f8e85ebe8356b13',
                answerText:
                  "The tendency to forget information that doesn't align with our beliefs",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ebc68f8e85ebe8356b14',
                answerText:
                  'The tendency to seek, interpret, and remember information that confirms our existing beliefs',
                isCorrect: true,
                answerMessage: null,
              },
              {
                id: '66a2ebcf8f8e85ebe8356b15',
                answerText: 'The tendency to change our beliefs based on new information',
                isCorrect: false,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ebde8f8e85ebe8356b16',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which of the following is NOT a way confirmation bias can lead us astray?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html:
              '<p>Which of the following is NOT a way confirmation bias can lead us astray?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ebf98f8e85ebe8356b17',
                answerText:
                  "It can make our beliefs less robust to counter-arguments, since they haven't been exposed to strong criticisms",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec098f8e85ebe8356b18',
                answerText:
                  "It can cause us to miss crucial information in decision-making, since we won't notice information that challenges us",
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec3c8f8e85ebe8356b19',
                answerText:
                  'It can cause us to lose confidence in our positions, due to focusing on what challenges them',
                isCorrect: true,
                answerMessage: null,
              },
            ],
            blockType: 'multChoice',
          },
          {
            id: '66a2ec758f8e85ebe8356b1a',
            reviewQuestion: {
              root: {
                type: 'root',
                format: '',
                indent: 0,
                version: 1,
                children: [
                  {
                    type: 'paragraph',
                    format: '',
                    indent: 0,
                    version: 1,
                    children: [
                      {
                        mode: 'normal',
                        text: 'Which scenario demonstrates confirmation bias?',
                        type: 'text',
                        style: '',
                        detail: 0,
                        format: 0,
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    textFormat: 0,
                  },
                ],
                direction: 'ltr',
              },
            },
            reviewQuestion_html: '<p>Which scenario demonstrates confirmation bias?</p>',
            blockName: null,
            answers: [
              {
                id: '66a2ec958f8e85ebe8356b1b',
                answerText:
                  'A scientist changes their hypothesis after finding contradictory evidence',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2ec9c8f8e85ebe8356b1c',
                answerText:
                  'A voter watches debates from all political parties before deciding who to vote for',
                isCorrect: false,
                answerMessage: null,
              },
              {
                id: '66a2eca68f8e85ebe8356b1d',
                answerText:
                  "An investor reads only positive news about a company they've invested in, ignoring negative reports",
                isCorrect: true,
                answerMessage:
                  'Good! This investor is sleepwalking to disaster, by not exposing themselves to information that challenges them.',
              },
            ],
            blockType: 'multChoice',
          },
        ],
        atom: {
          shortSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'paragraph',
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  textFormat: 0,
                },
              ],
              direction: 'ltr',
            },
          },
          shortSummary_html:
            '<p>Confirmation bias leads us to favor information that supports our existing beliefs, potentially distorting our worldview.</p>',
          mediumSummary: {
            root: {
              type: 'root',
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  tag: 'ul',
                  type: 'list',
                  start: 1,
                  format: '',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      value: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 2,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                    {
                      type: 'listitem',
                      value: 3,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          mode: 'normal',
                          text: 'To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.',
                          type: 'text',
                          style: '',
                          detail: 0,
                          format: 0,
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                    },
                  ],
                  listType: 'bullet',
                  direction: 'ltr',
                },
              ],
              direction: 'ltr',
            },
          },
          mediumSummary_html:
            '<ul class="list-bullet"><li value=1>Confirmation bias is our tendency to seek, interpret, and remember information that confirms our prior beliefs while ignoring contradictory evidence.</li><li value=2>This bias can create echo chambers, especially on social media, and reinforce incorrect or harmful beliefs.</li><li value=3>To combat confirmation bias, we must actively seek diverse perspectives and challenge our own assumptions.</li></ul>',
          longSummary: null,
          longSummary_html: '',
          source: 5,
          specificSection: ' 2.2 Overcoming Cognitive Biases and Engaging in Critical Reflection',
        },
        flashcards: [13, 14, 17],
        updatedAt: '2024-08-02T11:02:37.884Z',
        createdAt: '2024-07-25T22:54:55.824Z',
      },
      learningPhase: {
        id: 1,
        name: 'Recall',
        description: null,
        stabilityThreshold: 14,
        stage: 1,
        updatedAt: '2024-08-02T10:54:45.823Z',
        createdAt: '2024-08-02T10:54:45.823Z',
      },
      updatedAt: '2024-08-02T10:56:05.749Z',
      createdAt: '2024-07-27T00:57:28.221Z',
    },
    current: {
      due: '2024-08-30T00:20:32.083Z',
      reps: 2,
      state: 2,
      lapses: 0,
      stability: 19.63012817,
      difficulty: 3.15569146,
      last_review: '2024-08-07T00:20:32.083Z',
      elapsed_days: 1,
      scheduled_days: 23,
    },
    log: [
      {
        due: '2024-08-05T14:01:53.275Z',
        state: 2,
        rating: 4,
        review: '2024-08-07T00:20:32.083Z',
        stability: 10.9355,
        difficulty: 3.9437,
        elapsed_days: 1,
        scheduled_days: 13,
        last_elapsed_days: 0,
      },
      {
        due: '2024-08-05T14:01:24.247Z',
        state: 0,
        rating: 4,
        review: '2024-08-05T14:01:53.275Z',
        stability: 14,
        difficulty: 0,
        elapsed_days: 0,
        scheduled_days: 0,
        last_elapsed_days: 0,
      },
    ],
    updatedAt: '2024-08-07T00:20:32.205Z',
    createdAt: '2024-08-05T14:01:24.263Z',
  },
]
